name = "just-ears-keepalive"
main = "worker/index.js"
compatibility_date = "2025-11-04"

[triggers]
crons = ["*/14 * * * *"] # every 14 mins

[vars]
# n.b this can be multiple URLs ; separated but worker/index.js will need updating
N8N_URL = "https://n8n-3ote.onrender.com/healthz"
VOICE_AGENT_BACKEND_URL = "https://just-ears-receptionist.onrender.com/api/health"
